version: "3.3"

services:
  api:
    build:
      context: ../backend
      dockerfile: src/TalentDataTracker.API/Dockerfile
    container_name: talent-data-tracker-api
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=TalentDataDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - webnet

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: talent-data-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Developer"
    volumes:
      - sqlserver-data:/var/opt/mssql
    ports:
      - "1433:1433"
    networks:
      - webnet

volumes:
  sqlserver-data:

networks:
  webnet: